Nomina2018/Controllers/SalaryTabulatorController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using IMASD.DATA;
using IMASD.DATA.Entities;
using Services.Interface;
using Nomina2018.Mapping;
using Nomina2018.Models;
using Nomina2018.Models.JSON;
using System.Text;
using IMASD.Base.Utilities;
using IMASD.Base.DataTablesDTO;

namespace Nomina2018.Controllers
{
    public class SalaryTabulatorController : Controller
    {
        private readonly ISalaryTabulatorService salaryTabuladorService;
        private readonly IJobService jobService;
        private StringBuilder sb;
        public SalaryTabulatorController(ISalaryTabulatorService salaryTabuladorService, IJobService jobService)
        {
            this.jobService = jobService;
            this.salaryTabuladorService = salaryTabuladorService;
            sb = new StringBuilder();
        }
        // GET: SalaryTabulator
        public ActionResult Index()
        {
            sb.Clear();
            sb.Append("Retrieve Salary tabulators");
            SeriLogHelper.WriteInformation(null,sb.ToString());
            var salaryTabulatorsDTO = new List<SalaryTabulatorDTO>();
            return View(salaryTabulatorsDTO);
        }
        [HttpPost]
        public JsonResult getAll(DataTableInput input)
        {
            DataTableOutput<SalaryTabulator> salaryTabulators = new DataTableOutput<SalaryTabulator>();
           DataTableOutput<SalaryTabulatorDTO> salaryTabulatorsDTO = new DataTableOutput<SalaryTabulatorDTO>();
            try
            {
                salaryTabulators = salaryTabuladorService.GetSalarysTabulators(input);
                salaryTabulatorsDTO = AutoMapperConfiguration.Instance.Mapper.Map<DataTableOutput<SalaryTabulatorDTO>>(salaryTabulators);

            }
            catch (Exception e)
            {
                sb.Clear();
                sb.Append("An error has ocurred when it try to retrieve Salary Tabulators");
                SeriLogHelper.WriteError(e, sb.ToString());
                return new JsonHttpStatusResult(e.Message, HttpStatusCode.InternalServerError);
            }
            return Json(salaryTabulatorsDTO, JsonRequestBehavior.DenyGet);
        }

        // GET: SalaryTabulator/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                sb.Clear();
                sb.Append("BadRequest: It needs the Id for request the SalaryTabulator details");
                SeriLogHelper.WriteError(null, sb.ToString());
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var salaryTabulator = salaryTabuladorService.Get(x => x.Id == id );
            var salaryTabulatorDTO = AutoMapperConfiguration.Instance.Mapper.Map<SalaryTabulatorDTO>(salaryTabulator);
            if (salaryTabulatorDTO == null)
            {
                sb.Clear();
                sb.AppendFormat("Not found the salary tabulator with id {0}", id);
                SeriLogHelper.WriteWarning(null, sb.ToString());
                return HttpNotFound();
            }
            return View(salaryTabulatorDTO);
        }

        // GET: SalaryTabulator/Create
        [ValidateRequestAjax]
        public ActionResult Create()
        {
            var jobs = jobService.GetMany(x=>x.Active==true);
            var jobsDTO = AutoMapperConfiguration.Instance.Mapper.Map<IEnumerable<JobDTO>>(jobs);
            ViewBag.JobId = new SelectList(jobsDTO, "Id", "Name");
            return View();
        }
        [HttpPost]
        [ValidateAjax]
        public JsonResult CreateJson(SalaryTabulatorDTO salaryTabuladorDTO)
        {
            if ((int) salaryTabuladorDTO.TabulatorLevel==0)
            {
                sb.Clear();
                sb.Append("Is required a tabulator level to create a salary tabulator");
                SeriLogHelper.WriteWarning(null, sb.ToString());
                var data = new ErrorByKey[1] { new ErrorByKey { key = "TabulatorLevel", errors = new string[1] { "Requerido" } } };
                return new JsonHttpStatusResult(data, HttpStatusCode.BadRequest);
            }
            var employee = AutoMapperConfiguration.Instance.Mapper.Map<SalaryTabulator>(salaryTabuladorDTO);
            salaryTabuladorService.Insert(employee);
            return Json(employee, JsonRequestBehavior.DenyGet);
        }
        
        // GET: SalaryTabulator/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                sb.Clear();
                sb.Append("BadRequest: It needs the Id for edit a Salary Tabulator");
                SeriLogHelper.WriteError(null, sb.ToString());
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SalaryTabulator salaryTabulator = salaryTabuladorService.Get(x=>x.Id==id );
            if (salaryTabulator == null)
            {
                sb.Clear();
                sb.AppendFormat("Salary tabulator  do not found with the id {0}", id);
                SeriLogHelper.WriteWarning(null, sb.ToString());
                return HttpNotFound();
            }
            var salaryTabulatorDTO = AutoMapperConfiguration.Instance.Mapper.Map<SalaryTabulatorDTO>(salaryTabulator);
            var jobs = jobService.GetMany(x => x.Active == true);
            var jobsDTO = AutoMapperConfiguration.Instance.Mapper.Map<IEnumerable<JobDTO>>(jobs);
            
            ViewBag.JobId = new SelectList(jobsDTO, "Id", "Name", salaryTabulatorDTO.JobId);
            return View(salaryTabulatorDTO);
        }

        [HttpPost]
        [ValidateAjax]
        public JsonResult EditJson(SalaryTabulatorDTO salaryTabulatorDTO)
        {
            if ((int)salaryTabulatorDTO.TabulatorLevel==0)
            {
                sb.Clear();
                sb.Append("It needs a tabulator level to edit a salary tabulator");
                SeriLogHelper.WriteWarning(null, sb.ToString());
                var data = new ErrorByKey[1] { new ErrorByKey { key = "TabulatorLevel", errors = new string[1] { "Requerido" } } };
                return new JsonHttpStatusResult(data, HttpStatusCode.BadRequest);
            }
            var salaryTabulator = AutoMapperConfiguration.Instance.Mapper.Map<SalaryTabulator>(salaryTabulatorDTO);
            salaryTabuladorService.Update(salaryTabulator);
            return Json(salaryTabulatorDTO,JsonRequestBehavior.DenyGet);
        }

        // GET: SalaryTabulator/Active/true/5
        [HttpDelete]
        [Route("SalaryTabulator/Active/{active}/{id}")]
        public ActionResult Delete(bool active,int? id)
        {
            if (id == null)
            {
                sb.Clear();
                sb.Append("It needes a Id to delete a Salary tabulator");
                SeriLogHelper.WriteError(null, sb.ToString());
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            try
            {
                SalaryTabulator salaryTabulator = salaryTabuladorService.Get(x => x.Id == id && x.Active == !active);
                if (salaryTabulator == null)
                {
                    return HttpNotFound();
                }
                salaryTabulator.Active = active;
                salaryTabuladorService.Update(salaryTabulator);
                SalaryTabulatorDTO salaryTabulatorDTO = AutoMapperConfiguration.Instance.Mapper.Map<SalaryTabulatorDTO>(salaryTabulator);
                return Json(salaryTabulatorDTO, JsonRequestBehavior.DenyGet);

            }
            catch (Exception e)
            {
                sb.Clear();
                sb.Append(e.ToString());
                return new JsonHttpStatusResult(sb.ToString(), HttpStatusCode.InternalServerError);
            }
            
            
            
        }

        // POST: SalaryTabulator/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            SalaryTabulator salaryTabulator = salaryTabuladorService.Get(x=>x.Id==id && x.Active==true);
            if (salaryTabulator==null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            salaryTabuladorService.Delete(salaryTabulator);
            return RedirectToAction("Index");
        }

        //protected override void Dispose(bool disposing)
        //{
        //    if (disposing)
        //    {
        //        db.Dispose();
        //    }
        //    base.Dispose(disposing);
        //}
    }
}

Nomina2018/Views/SalaryTabulator/Create.cshtml
@model SalaryTabulatorDTO

@{
    ViewBag.Title = "Create";
    Layout = "";
}



@using (Html.BeginForm("CreateJson", "SalaryTabulator", null, FormMethod.Post, new { Id = "createForm" }))
{

    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title" id="modalLabel">Nuevo tabulador salarial</h4>
    </div>
    <div class="modal-body">
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Key, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Key, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Key, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.JobId, "Puesto", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("JobId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.JobId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.TabulatorLevel, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EnumDropDownListFor(model => model.TabulatorLevel, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.TabulatorLevel, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Hourlywages, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Hourlywages, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Hourlywages, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.AnnualHolidayBonus, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.AnnualHolidayBonus, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.AnnualHolidayBonus, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.AnnualBonusDays, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.AnnualBonusDays, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.AnnualBonusDays, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.AnnualVacationDays, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.AnnualVacationDays, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.AnnualVacationDays, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Active, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.Active)
                        @Html.ValidationMessageFor(model => model.Active, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>

    </div>
    <div class="modal-footer">


        <div id="spinner"><div class="bar1"></div><div class="bar2"></div><div class="bar3"></div><div class="bar4"></div><div class="bar5"></div><div class="bar6"></div><div class="bar7"></div><div class="bar8"></div></div>


        <button type="submit" class="btn btn-primary">Guardar</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
    </div>

}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Nomina2018/Views/SalaryTabulator/Details.cshtml
@model SalaryTabulatorDTO

@{
    ViewBag.Title = "Details";
    Layout = "";
}

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title" id="modalLabel">Detalles del </h4>tabulador salarial
</div>

<div class="modal-body">
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Job.Key)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Job.Key)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Key)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Key)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TabulatorLevel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TabulatorLevel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Hourlywages)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Hourlywages)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AnnualHolidayBonus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AnnualHolidayBonus)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AnnualBonusDays)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AnnualBonusDays)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AnnualVacationDays)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AnnualVacationDays)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Active)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Active)
        </dd>

    </dl>
</div>
<div class="modal-footer">

    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
</div>

Nomina2018/Views/SalaryTabulator/Edit.cshtml
@model SalaryTabulatorDTO

@{
    ViewBag.Title = "Editar";
    Layout = "";
}

@using (Html.BeginForm("EditJson", "SalaryTabulator", null, FormMethod.Post, new { Id = "editForm" }))
{
    @Html.AntiForgeryToken()

    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title" id="modalLabel">Editar tabulador salarial</h4>
    </div>
    <div class="modal-body">
        <div class="form-horizontal">
            
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)
            @Html.HiddenFor(model => model.Active)

            <div class="form-group">
                @Html.LabelFor(model => model.Key, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Key, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Key, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.JobId, "Puesto", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("JobId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.JobId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.TabulatorLevel, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EnumDropDownListFor(model => model.TabulatorLevel, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.TabulatorLevel, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Hourlywages, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Hourlywages, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Hourlywages, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.AnnualHolidayBonus, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.AnnualHolidayBonus, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.AnnualHolidayBonus, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.AnnualBonusDays, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.AnnualBonusDays, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.AnnualBonusDays, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.AnnualVacationDays, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.AnnualVacationDays, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.AnnualVacationDays, "", new { @class = "text-danger" })
                </div>
            </div>


        </div>
    </div>

    <div class="modal-footer">
        <button type="submit" class="btn btn-primary">Guardar</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
    </div>

}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Nomina2018/Views/SalaryTabulator/Index.cshtml
@model IEnumerable<SalaryTabulatorDTO>

@{
    ViewBag.Title = "Index";
}
@section Styles{
    <link href="~/Content/DataTables/media/css/jquery.dataTables.min.css" rel="stylesheet" />
    <link href="~/Content/Spinner.css" rel="stylesheet" />

    <style>
        .dataTables_processing {
            top: 110px !important;
            z-index: 11000 !important;
        }
    </style>
}

<h2>Tabulador salarial</h2>
<tr/>
<div class="panel panel-default" style="padding-bottom:60px">
    <div   class="row">
        <div class="col-md-2 col-md-offset-9 col-sm-2 col-sm-offset-9 col-xs-4 col-xs-offset-7">
            <button style="margin:25px" data-toggle="tooltip" data-placement="left" title="Crear" aria-label="Left Align" class="buttonNew btn btn-success btn-sm btn-size-table" data-url="@Url.Action("Create", "SalaryTabulator", new { })">
                Nuevo tabulador salarial
            </button>
        </div> 
    </div>
    <div class="table-responsive">
        <table id="salaryTabulatorsDT" class="table table-striped" data-url="@Url.Action("getAll", "SalaryTabulator", new { })">
            <thead>
                <tr class="bg-primary text-white">
                    <th>
                        @Html.DisplayNameFor(model => model.JobId)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Key)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.TabulatorLevel)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Hourlywages)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.AnnualHolidayBonus)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.AnnualBonusDays)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.AnnualVacationDays)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Active)
                    </th>
                    <th></th>
                </tr>
            </thead>
        </table>
    </div>
        

        <input id="urlEditSalaryTabulator" type="hidden" value="@Url.Action("Edit", "SalaryTabulator")" />
        <input id="urlDetailsSalaryTabulator" type="hidden" value="@Url.Action("Details", "SalaryTabulator")" />
        <input id="urlActiveSalaryTabulator" type="hidden" value="@Url.Action("Active", "SalaryTabulator")" />

    </div>

<div class="container-fluid">

    <!-- The modal -->
    <div class="modal fade" id="flipFlop" tabindex="-1" data-backdrop="static" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div id="load" class="modal-content">

            </div>
        </div>
    </div>

</div>
<div id="deleteModal" style="display:none;">

    <div class="modal-body">
        <span class="text-center text-modal"></span>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-primary activeButton" id="activeButton"><span class="text-active"></span></button>
        <button type="button" data-dismiss="modal" class="btn">Cancelar</button>
    </div>
</div>

@section Scripts{

    <script src="~/Scripts/DataTables/media/js/jquery.dataTables.min.js" type="text/javascript"></script>

    <script src="~/Scripts/DatatablesConfig/customDataTable.js" type="text/javascript"></script>

    <script src="~/Scripts/SalaryTabulator/index.js" type="text/javascript"></script>

}