Nomina2018/Controllers/ConfigController.cs
using IMASD.Base.DataTablesDTO;
using IMASD.Base.ENUMS;
using IMASD.Base.Utilities;
using IMASD.DATA.Entities;
using Nomina2018.Mapping;
using Nomina2018.Models;
using Nomina2018.Models.JSON;
using Services.Interface;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace Nomina2018.Controllers
{
    public class ConfigController : Controller
    {
        private readonly IPaymentService _paymentService;
        private readonly IDepartamentService _departamentService;
        private StringBuilder sb;
        public ConfigController(IPaymentService _paymentService, IDepartamentService _departamentService)
        {
            this._paymentService = _paymentService;
            this._departamentService = _departamentService;
            sb = new StringBuilder();

        }
        // GET: Config
        public ActionResult Payment()
        {
            sb.Clear();
            sb.Append("Retrieve Payments");
            SeriLogHelper.WriteInformation(null, sb.ToString());
            var employees = new List<EmployeeDTO>();
            ViewBag.DepartamentId = new SelectList(AutoMapperConfiguration.Instance.Mapper.Map<IEnumerable<DepartamentDTO>>(_departamentService.GetMany(x => x.Active == true)), "Id", "Name");
            var payments = new List<PaymentDTO>();
            return View(payments);
        }
        [HttpPost]
        public JsonResult CustomServerSideSearchAction(DataTableVM<PaymentSearch> model)
        {
            DataTableOutput<Payment> payments = new DataTableOutput<Payment>();
            DataTableOutput<PaymentDTO> paymentsDTO = new DataTableOutput<PaymentDTO>();
            try
            {
                payments = _paymentService.GetByFilters( model.Filters.Employee ?? null, model.Filters.DepartamentId ??null, model.dataTablesInput ?? null);
                paymentsDTO = AutoMapperConfiguration.Instance.Mapper.Map<DataTableOutput<PaymentDTO>>(payments);
            }
            catch (Exception e)
            {
                sb.Clear();
                sb.Append("An error has occurred when it try to retrieve payments");
                SeriLogHelper.WriteError(e, sb.ToString());
                return new JsonHttpStatusResult(e.Message, HttpStatusCode.BadRequest);

            }
            return Json(paymentsDTO, JsonRequestBehavior.DenyGet);
        }
    }
}

Nomina2018/Views/Config/Payment.cshtml
@model IEnumerable<PaymentDTO>

@{
    ViewBag.Title = "Pagos";
}
@section Styles{
    <link href="~/Content/DataTables/media/css/jquery.dataTables.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-datepicker.min.css" rel="stylesheet" />
    <link href="~/Content/Spinner.css" rel="stylesheet" />

    <style>
        .dataTables_processing {
            top: 110px !important;
            z-index: 11000 !important;
        }
    </style>
}
<h2>Pagos</h2>
<tr />
<div class="jumbotron">
    @using (Html.BeginForm("Search", "payment", null, FormMethod.Post, new { Id = "searchForm", @class = "form-horizontal" }))
    {

        <div class="form-group col-lg-6 col-md-6 col-sm-6 col-xs-12">
            <label class="control-label">Departamento:</label>
            @Html.DropDownList("DepartamentId", null, "-- Seleccione un departamento --", htmlAttributes: new { @class = "form-control" })
        </div>
        

            <div class="form-group col-lg-6 col-md-6 col-sm-6 col-xs-12">
                <label class="control-label">Nombre de empleado:</label>
                <div>
                    <input name="Employee" id="Employee" type="text" class="form-control">
                </div>
            </div>

                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <div class="col-md-9 col-sm-9 col-xs-12 ">
                            <input id="btnConsultar" type="submit" value="Consultar" class="btn btn-primary" data-url="@Url.Action("Create", "Employee", new { })" />
                        </div>
                    </div>
    }

</div>

<div class="panel panel-default" style="padding-bottom:60px">

    <div class="row">
        <div class="row">
            <div class="col-md-2 col-md-offset-9 col-sm-2 col-sm-offset-9 col-xs-4 col-xs-offset-7">

            </div>

        </div>
    </div>

    <div class="table-responsive">
        <table id="paymentsDT" class="table  table-striped" data-url="@Url.Action("CustomServerSideSearchAction", "Config", new { })">
            <thead>
                <tr class="bg-primary text-white">
                    <th>
                        Nombres del @Html.DisplayNameFor(model => model.EmployeeId)
                    </th>
                    <th>
                       Apellidos del @Html.DisplayNameFor(model => model.EmployeeId)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.FrequencyofPayments)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.StarDate)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.EndDate)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.ProcessedDate)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.VoidDate)
                    </th>
                </tr>
            </thead>

        </table>
    </div>

</div>


@section Scripts{

    <script src="~/Scripts/DataTables/media/js/jquery.dataTables.min.js" type="text/javascript"></script>

    <script src="~/Scripts/DatatablesConfig/customDataTable.js" type="text/javascript"></script>

    <script src="~/Scripts/Config/payment.js" type="text/javascript"></script>

}